39 status arquivamento caixa
fga-eps-mds/2021.2-SysArq-Archives pull request #17
Opened 2022-04-10 22:06 UTC by Weslin-0101

## Descrição 

# O que foi modificado:
      . Adicionado o campo de Status dentro da model do Document

## Issue Correspondente

[39](https://github.com/fga-eps-mds/2021-2-sysarq-doc/issues/39)

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

## Anexos

## Comentários adicionais

2022-04-11 05:57 UTC, baraky requested changes

2022-04-11 05:57 UTC, baraky commented on archives_app/documents_models.py
> +                                 null=True, related_name='unfiled_unity')
Não é para tornar esses atributos presentes em todos os tipos de documentos. Eles estarão apenas no Processo Administrativo e Arquivamento de Caixas.

2022-04-11 05:57 UTC, baraky commented on archives_app/documents_models.py
> +    box_process_number = models.CharField(max_length=15, blank=True, null=True)
Por que esse novo atributo?

2022-04-11 05:57 UTC, baraky commented on archives_app/documents_models.py
> -                                 null=True, related_name='unfiled_unity')
Como comentado lá em cima, esses atributos permanecem aqui.

2022-04-11 23:45 UTC, Weslin-0101 commented on archives_app/documents_models.py
> +                                 null=True, related_name='unfiled_unity')
Irei fazer as mudanças

2022-04-11 23:47 UTC, Weslin-0101 commented on archives_app/documents_models.py
> +    box_process_number = models.CharField(max_length=15, blank=True, null=True)
![image](https://user-images.githubusercontent.com/70270543/162850869-57412a05-298a-40ec-b292-3b3df291904f.png)
Eu apenas segui a lógica que eles implementaram dentro do Processo Administrativo, pois eles chamam esse atributo quando vai por o arquivo no status de "Desarquivado"

2022-04-12 03:25 UTC, baraky commented on archives_app/documents_models.py
> +    box_process_number = models.CharField(max_length=15, blank=True, null=True)
Entendi, faz sentido

2022-04-19 00:54 UTC, baraky approved these changes

2022-04-19 00:55 UTC, merged