90 alterar informações no campo obrigatório caixa
fga-eps-mds/2021.2-SysArq-Archives pull request #6
Opened 2022-03-27 18:12 UTC by black258br

## Descrição 

## Issue Correspondente

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

2022-03-28 20:52 UTC, baraky requested changes

2022-03-28 20:52 UTC, baraky commented on archives_app/fields_models.py
> +    cpf = models.CharField(max_length=16)
Era para essa modificação ter subido mesmo? Pergunto porque acredito que estamos tratando já no front para que seja enviado apenas os 11 números.

2022-03-28 21:10 UTC, baraky commented on archives_app/fields_models.py
> +    cpf = models.CharField(max_length=16)
Atualizar também os [testes](https://github.com/fga-eps-mds/2021.2-SysArq-Archives/blob/main/tests/urls_tests.py#L255-L321) para o novo formato.

2022-03-28 22:12 UTC, black258br commented
@baraky Corrigido o teste e retirado o field models do cpf, nao sei como isso foi parar aí kkkk

2022-03-29 03:36 UTC, baraky approved these changes

2022-03-29 03:36 UTC, merged